name: CI

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # https://github.com/actions/setup-go
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Check golang version/env
        run: |
          set -x
          go version
          go env

      - name: build
        run: make build

      - name: lint
        run: make lint

      - name: test
        run: make test
